services:
  main:
    image: ${MAIN_IMAGE_NAME}
    build:
      context: ${CONTEXT_DIR}
      args:
        HTTP_PROXY: ${BENCHFLOW_TASK_HTTP_PROXY:-}
        HTTPS_PROXY: ${BENCHFLOW_TASK_HTTPS_PROXY:-}
        NO_PROXY: ${BENCHFLOW_TASK_NO_PROXY:-}
        http_proxy: ${BENCHFLOW_TASK_HTTP_PROXY:-}
        https_proxy: ${BENCHFLOW_TASK_HTTPS_PROXY:-}
        no_proxy: ${BENCHFLOW_TASK_NO_PROXY:-}
      extra_hosts:
        - "host.docker.internal:host-gateway"
    pull_policy: build
    command: [ "sh", "-c", "sleep infinity" ]
